name: Mostrar Fecha Actual

# Disparador: Se ejecuta manualmente desde la interfaz de GitHub Actions
on:
  workflow_dispatch:

# Trabajo (Job)
jobs:
  mostrar_hora:
    name: Obtener Fecha y Hora
    # Ejecutar en la última versión de Ubuntu
    runs-on: ubuntu-latest 
    
    steps:
      - name: Ejecutar comando 'date' e imprimir
        # El comando 'date' en Linux/Unix muestra la fecha y hora actual.
        run: echo "La fecha y hora actual en la máquina virtual es: $(date)"
